### ISSUE TITLE
Pochi gets stuck on loading after stopping a request until VS Code is restarted or a new task is created

### ISSUE THREAD

**Issue by yusifahmadov** [TabbyML/pochi#475]
**Describe the bug**
When stopping an ongoing request in Pochi and attempting to send a new prompt, the application often (but not always) gets stuck on the loading state. The only way to continue is to either create a new task or restart VS Code.

**Steps to Reproduce**

1. Open Pochi in VS Code.
2. Enter a prompt and send a request.
3. While Pochi is processing, stop/interrupt the request.
4. Enter a new prompt and send it.
5. Observe that in most cases Pochi remains stuck in the loading state.

**Expected behavior**
After stopping a request, sending a new prompt should work normally without requiring a restart or creating a new task.

**Information about your version**
0.8.65

**Additional context**

- The issue occurs most times, but not every time.
- Restarting VS Code or creating a new task temporarily resolves the issue.
- I am really sick of this issue — I can’t use the extension properly because of it.

**Comment by wsxiaoys** [comment]
Fixed in latest vscode release

**Comment by yusifahmadov** [comment]
<img width="731" height="858" alt="Image" src="https://github.com/user-attachments/assets/b39f480a-c9f1-4006-a9f1-f1f5f1ef28dd" />

I just came back with hope and tried your product again, but the same issues still exist. I don’t think you guys even test what you’re building. You introduced the “Show all tasks” feature, but when I have two open tasks and try to send “hi,” it goes to the wrong chat. I really hope you start testing your product before merging any pull requests into the system, otherwise, it’s useless.

**Comment by yusifahmadov** [comment]
<img width="731" height="858" alt="Image" src="https://github.com/user-attachments/assets/c08335fc-ce94-4c74-a0a3-b8d6164d6dd4" />

<img width="731" height="537" alt="Image" src="https://github.com/user-attachments/assets/19c2545c-4672-431c-ad1a-a911773633fd" />


'Hi' message goes to both chats. What is that

**Comment by wsxiaoys** [comment]
Hi - could you share the version you were using? Note the pre-release version (0.11) is not stable yet, I recommend stay with the release version for your day to day work. And consider share your feedback in discord for more engaging debugging.
